import React, { useEffect, useRef, useState } from "react";
import * as THREE from "three";
import { Flame, Sparkles, Rotate3d } from "lucide-react";
import steakTextureImg from "../assets/images/bonfire_steak3d_1782203586973.jpg";

export default function InteractiveSteak3D() {
  const mountRef = useRef<HTMLDivElement>(null);
  const [clickCount, setClickCount] = useState(0);
  const [isHovered, setIsHovered] = useState(false);
  const [sizzleActive, setSizzleActive] = useState(false);
  const [gyroAvailable, setGyroAvailable] = useState(false);
  const [useFallback, setUseFallback] = useState(false);

  // References to pass values into the Three.js tick loop safely
  const scrollYRef = useRef(0);
  const mouseRef = useRef({ x: 0, y: 0 });
  const touchStartRef = useRef({ x: 0, y: 0 });
  const tiltRef = useRef({ x: 0, y: 0 });
  const impulseRef = useRef(0); // Boost rotation when clicked
  const scaleTargetRef = useRef(1.0); // Target scale for click bounce
  const sizzleActiveRef = useRef(false);
  const gyroAvailableRef = useRef(false);

  useEffect(() => {
    sizzleActiveRef.current = sizzleActive;
  }, [sizzleActive]);

  // Path to our stunning steak image generated by the system
  const steakTexturePath = steakTextureImg;

  // Check if device supports DeviceOrientation API for gyro interaction on mobile
  useEffect(() => {
    const handleOrientation = (e: DeviceOrientationEvent) => {
      try {
        if (e.beta !== null && e.gamma !== null) {
          setGyroAvailable(true);
          gyroAvailableRef.current = true;
          // Normalize rotation to soft movement range (-0.5 to 0.5)
          const xTilt = Math.max(-30, Math.min(30, e.gamma)) / 30;
          const yTilt = Math.max(-30, Math.min(30, e.beta - 45)) / 30; // centered around 45 deg tilt
          tiltRef.current = { x: xTilt * 0.4, y: yTilt * 0.4 };
        }
      } catch (err) {
        // Suppress any errors
      }
    };

    try {
      window.addEventListener("deviceorientation", handleOrientation);
    } catch (err) {
      console.warn("DeviceOrientation event listener not allowed:", err);
    }
    return () => {
      try {
        window.removeEventListener("deviceorientation", handleOrientation);
      } catch (err) {
        // Suppress any errors
      }
    };
  }, []);

  // Sync scroll offset
  useEffect(() => {
    const handleScroll = () => {
      scrollYRef.current = window.scrollY;
    };
    window.addEventListener("scroll", handleScroll, { passive: true });
    return () => window.removeEventListener("scroll", handleScroll);
  }, []);

  // Main Three.js setup
  useEffect(() => {
    if (!mountRef.current || useFallback) return;

    let width = mountRef.current.clientWidth || 400;
    let height = mountRef.current.clientHeight || 400;

    // Create scene
    const scene = new THREE.Scene();

    // Subtle dark mist sky background inside Three.js
    scene.fog = new THREE.FogExp2(0x111111, 0.15);

    // Create camera
    const camera = new THREE.PerspectiveCamera(45, width / height, 0.1, 100);
    camera.position.z = 4.5;

    // Create WebGL Renderer
    let renderer: THREE.WebGLRenderer;
    try {
      renderer = new THREE.WebGLRenderer({ antialias: true, alpha: true });
      renderer.setSize(width, height);
      renderer.setPixelRatio(Math.min(window.devicePixelRatio, 2));
      renderer.shadowMap.enabled = true;
      renderer.shadowMap.type = THREE.PCFSoftShadowMap;
      mountRef.current.appendChild(renderer.domElement);
    } catch (e) {
      console.warn("WebGL not supported. Loading interactive premium 3D fallback...", e);
      setUseFallback(true);
      return;
    }

    // Set up lights
    // 1. Warm campfire glow from below
    const bottomOrangeLight = new THREE.PointLight(0xff4500, 4, 10);
    bottomOrangeLight.position.set(0, -1.5, 0.5);
    scene.add(bottomOrangeLight);

    // 2. High-end gold studio key light from upper right
    const goldenLight = new THREE.DirectionalLight(0xffaa00, 3);
    goldenLight.position.set(2, 3, 1.5);
    scene.add(goldenLight);

    // 3. Ambient lighting to fill dark parts
    const darkAmbient = new THREE.AmbientLight(0x221a15, 1.2);
    scene.add(darkAmbient);

    // Let's create the 3D Steak!
    // Since we want look realistic, we'll create a fat, smooth 3D shape representing a thick, premium cut of steak.
    // We'll map the beautiful generated picture onto it.
    const steakGroup = new THREE.Group();
    scene.add(steakGroup);

    // Load the generated T-Bone prime steak texture
    const textureLoader = new THREE.TextureLoader();
    let steakTexture: THREE.Texture | null = null;
    
    steakTexture = textureLoader.load(steakTexturePath, (tex) => {
      tex.wrapS = THREE.ClampToEdgeWrapping;
      tex.wrapT = THREE.ClampToEdgeWrapping;
      // High-quality filter
      tex.minFilter = THREE.LinearMipmapLinearFilter;
      tex.generateMipmaps = true;
    });

    // Create a juicy rounded-flat Steak cylinder
    // Top & Bottom will display the glorious grilled steak details, sides will display a charcoal brown texture.
    const steakGeometry = new THREE.CylinderGeometry(1.2, 1.2, 0.35, 32, 1, false);
    
    // Create materials: Top/bottom face + side face
    const topMaterial = new THREE.MeshStandardMaterial({
      map: steakTexture,
      roughness: 0.25,
      metalness: 0.1,
      bumpMap: steakTexture,
      bumpScale: 0.08,
    });

    const sideMaterial = new THREE.MeshStandardMaterial({
      color: 0x1d1310, // Rich internal charcoal-brown roasted color
      roughness: 0.7,
      metalness: 0.0,
      bumpMap: steakTexture,
      bumpScale: 0.05
    });

    // Apply multiple materials to the cylinder: [Sides, Top, Bottom]
    const materials = [sideMaterial, topMaterial, topMaterial];
    
    const steakMesh = new THREE.Mesh(steakGeometry, materials);
    steakMesh.rotation.x = Math.PI / 2.3; // Tilt so the top face faces somewhat forward
    steakMesh.castShadow = true;
    steakMesh.receiveShadow = true;
    steakGroup.add(steakMesh);

    // Create a rotating cast iron Grill Grate underneath the steak (for unmatched luxury feel)
    const grateGeometry = new THREE.RingGeometry(0.8, 1.4, 32);
    const grateMaterial = new THREE.MeshStandardMaterial({
      color: 0x111111,
      roughness: 0.9,
      metalness: 0.8,
      side: THREE.DoubleSide
    });
    const grateMesh = new THREE.Mesh(grateGeometry, grateMaterial);
    grateMesh.position.y = -0.5;
    grateMesh.rotation.x = Math.PI / 2;
    scene.add(grateMesh);

    // Glowing ember plate underneath the grate
    const emberGeometry = new THREE.CircleGeometry(1.3, 16);
    const emberMaterial = new THREE.MeshBasicMaterial({
      color: 0xcc2200,
      side: THREE.DoubleSide,
      transparent: true,
      opacity: 0.4
    });
    const emberMesh = new THREE.Mesh(emberGeometry, emberMaterial);
    emberMesh.position.y = -0.55;
    emberMesh.rotation.x = Math.PI / 2;
    scene.add(emberMesh);

    // 4. Glowing Flame Particles floating upwards
    const particleCount = 65;
    const particleGeometry = new THREE.BufferGeometry();
    const positions = new Float32Array(particleCount * 3);
    const speeds = new Float32Array(particleCount);
    const scales = new Float32Array(particleCount);

    for (let i = 0; i < particleCount; i++) {
      // Place randomly inside a cylinder zone under/around the steak
      const theta = Math.random() * Math.PI * 2;
      const radius = Math.random() * 0.9;
      positions[i * 3] = Math.cos(theta) * radius; // x
      positions[i * 3 + 1] = Math.random() * 2.5 - 1.2; // y
      positions[i * 3 + 2] = Math.sin(theta) * radius; // z

      speeds[i] = 0.015 + Math.random() * 0.025; // Speed upward
      scales[i] = 0.5 + Math.random() * 1.5; // Particle size scale
    }

    particleGeometry.setAttribute("position", new THREE.BufferAttribute(positions, 3));

    // Simple canvas texture for smooth rounded particles with nice glowing fade margins
    const createParticleTexture = () => {
      const canvas = document.createElement("canvas");
      canvas.width = 16;
      canvas.height = 16;
      const ctx = canvas.getContext("2d");
      if (!ctx) {
        return new THREE.CanvasTexture(canvas);
      }
      const grad = ctx.createRadialGradient(8, 8, 0, 8, 8, 8);
      grad.addColorStop(0, "rgba(255, 140, 0, 1)");
      grad.addColorStop(0.4, "rgba(255, 69, 0, 0.8)");
      grad.addColorStop(1, "rgba(0,0,0,0)");
      ctx.fillStyle = grad;
      ctx.fillRect(0, 0, 16, 16);
      return new THREE.CanvasTexture(canvas);
    };

    const particleMaterial = new THREE.PointsMaterial({
      size: 0.16,
      map: createParticleTexture(),
      transparent: true,
      blending: THREE.AdditiveBlending,
      depthWrite: false,
    });

    const fireParticles = new THREE.Points(particleGeometry, particleMaterial);
    scene.add(fireParticles);

    // Animation Tick loop
    let animationId: number;
    const clock = new THREE.Clock();

    const animate = () => {
      animationId = requestAnimationFrame(animate);

      const elapsedTime = clock.getElapsedTime();

      // Handle scale interpolation for snappy click bounce
      const scaleDiff = scaleTargetRef.current - steakGroup.scale.x;
      steakGroup.scale.x += scaleDiff * 0.15;
      steakGroup.scale.y += scaleDiff * 0.15;
      steakGroup.scale.z += scaleDiff * 0.15;

      // Handle impulse decay (extra spin when clicked)
      impulseRef.current *= 0.94;

      // Slow idle floating and continuous rotation
      const idleFloatY = Math.sin(elapsedTime * 1.8) * 0.08;
      steakGroup.position.y = idleFloatY;

      // Rotate steak: base idle rotation + extra spin impulse
      const spinSpeed = 0.012 + impulseRef.current;
      steakGroup.rotation.y += spinSpeed;
      // Gentle pitching
      steakGroup.rotation.z = Math.sin(elapsedTime * 0.9) * 0.05;

      // Parallax effect from scroll:
      // When scroll is triggered, rotate the steak around X and scale it slightly
      const scrollY = scrollYRef.current;
      // Control how scroll rotates the group
      steakGroup.rotation.x = (scrollY * 0.0016) + Math.PI / 24;
      
      // Dynamic zoom on scroll
      const scrollScaleFactor = 1.0 + Math.max(0, Math.min(scrollY * 0.0006, 0.25));
      if (scaleTargetRef.current === 1.0) {
        steakGroup.scale.set(scrollScaleFactor, scrollScaleFactor, scrollScaleFactor);
      }

      // Parallax from Mouse movement/Gyroscope:
      let targetTiltX = mouseRef.current.x * 0.35;
      let targetTiltY = mouseRef.current.y * 0.35;

      if (gyroAvailableRef.current) {
        targetTiltX = tiltRef.current.x;
        targetTiltY = tiltRef.current.y;
      }

      // Smooth interpolation for mouse tilting
      steakGroup.position.x += (targetTiltX - steakGroup.position.x) * 0.1;
      // combine mouse tilt and scroll translation
      const targetY = idleFloatY + (-targetTiltY);
      steakGroup.position.y += (targetY - steakGroup.position.y) * 0.1;

      // Light pulsing effect like real hot embers
      const emberIntensity = 3.5 + Math.sin(elapsedTime * 5.0) * 1.5 + (sizzleActiveRef.current ? 4.0 : 0);
      bottomOrangeLight.intensity = emberIntensity;
      emberMaterial.opacity = 0.3 + Math.sin(elapsedTime * 4.0) * 0.12 + (sizzleActiveRef.current ? 0.3 : 0);

      // Animate fire sparks drifting upwards
      const positions = particleGeometry.attributes.position.array as Float32Array;
      const count = particleGeometry.attributes.position.count;

      for (let i = 0; i < count; i++) {
        // move Y up
        let y = positions[i * 3 + 1];
        y += speeds[i] * (sizzleActiveRef.current ? 3.0 : 1.0);

        // sway side-to-side
        let x = positions[i * 3];
        x += Math.sin(elapsedTime * 2.0 + i) * 0.003;

        // Reset if goes too high
        if (y > 1.8) {
          y = -1.2;
          const theta = Math.random() * Math.PI * 2;
          const radius = Math.random() * 0.7;
          positions[i * 3] = Math.cos(theta) * radius;
          positions[i * 3 + 2] = Math.sin(theta) * radius;
        }

        positions[i * 3 + 1] = y;
        positions[i * 3] = x;
      }
      particleGeometry.attributes.position.needsUpdate = true;

      // Gently rotate grill grate
      grateMesh.rotation.z -= 0.002;

      try {
        renderer.render(scene, camera);
      } catch (renderError) {
        console.warn("WebGL render error, switching to fallback card.", renderError);
        setUseFallback(true);
      }
    };

    animate();

    // Handle Resize
    const handleResize = () => {
      if (!mountRef.current) return;
      width = mountRef.current.clientWidth;
      height = mountRef.current.clientHeight;
      renderer.setSize(width, height);
      camera.aspect = width / height;
      camera.updateProjectionMatrix();
    };
    window.addEventListener("resize", handleResize);

    return () => {
      window.removeEventListener("resize", handleResize);
      cancelAnimationFrame(animationId);
      if (mountRef.current && renderer.domElement) {
        try {
          mountRef.current.removeChild(renderer.domElement);
        } catch (_) {}
      }
      renderer.dispose();
      steakGeometry.dispose();
      topMaterial.dispose();
      sideMaterial.dispose();
      grateGeometry.dispose();
      grateMaterial.dispose();
      emberGeometry.dispose();
      emberMaterial.dispose();
      particleGeometry.dispose();
      particleMaterial.dispose();
    };
  }, [useFallback]);

  // Handle click to expand, spin, trigger sparks, and sound!
  const handleInteractionClick = () => {
    setClickCount((prev) => prev + 1);
    setSizzleActive(true);

    // Snap target scale up
    scaleTargetRef.current = 1.35;
    impulseRef.current = 0.18; // snap-spin!

    // Reset scale back to normal after physical bounce
    setTimeout(() => {
      scaleTargetRef.current = 1.0;
    }, 400);

    // Sizzle cooldown
    setTimeout(() => {
      setSizzleActive(false);
    }, 2000);
  };

  // Track cursor movement for nice 3D parallax tilt
  const handleMouseMove = (e: React.MouseEvent<HTMLDivElement>) => {
    if (!mountRef.current) return;
    const rect = mountRef.current.getBoundingClientRect();
    const x = ((e.clientX - rect.left) / rect.width) * 2 - 1;
    const y = -((e.clientY - rect.top) / rect.height) * 2 + 1;
    mouseRef.current = { x, y };
  };

  const handleMouseLeave = () => {
    mouseRef.current = { x: 0, y: 0 };
    setIsHovered(false);
  };

  const handleMouseEnter = () => {
    setIsHovered(true);
  };

  // Touch handlers for mobile
  const handleTouchStart = (e: React.TouchEvent<HTMLDivElement>) => {
    if (e.touches.length === 1) {
      touchStartRef.current = {
        x: e.touches[0].clientX,
        y: e.touches[0].clientY,
      };
    }
  };

  const handleTouchMove = (e: React.TouchEvent<HTMLDivElement>) => {
    if (!mountRef.current || e.touches.length !== 1) return;
    const rect = mountRef.current.getBoundingClientRect();
    const touchX = e.touches[0].clientX;
    const touchY = e.touches[0].clientY;

    const dx = (touchX - touchStartRef.current.x) / rect.width;
    const dy = (touchY - touchStartRef.current.y) / rect.height;

    mouseRef.current = {
      x: Math.max(-1.2, Math.min(1.2, dx * 3)),
      y: Math.max(-1.2, Math.min(1.2, -dy * 3)),
    };
  };

  return (
    <div className="relative w-full aspect-square max-w-[420px] md:max-w-[480px] mx-auto flex items-center justify-center">
      {/* Visual background shadows/glows for depth */}
      <div className="absolute inset-0 bg-radial from-orange-600/10 via-amber-600/5 to-transparent rounded-full blur-3xl pointer-events-none" />

      {useFallback ? (
        /* Fallback high-fidelity Interactive CSS 3D structure if WebGL is unavailable */
        <div
          id="3d-steak-fallback-card"
          onClick={handleInteractionClick}
          onMouseMove={handleMouseMove}
          onMouseEnter={handleMouseEnter}
          onMouseLeave={handleMouseLeave}
          className="relative cursor-pointer transition-all duration-300 w-4/5 aspect-square bg-[#0e0c0b] rounded-full border border-orange-500/10 p-4 shadow-xl flex items-center justify-center overflow-hidden"
          style={{
            transform: `perspective(1000px) rotateY(${mouseRef.current.x * 20}deg) rotateX(${-mouseRef.current.y * 20}deg) scale(${sizzleActive ? 1.15 : isHovered ? 1.05 : 1.0})`,
            boxShadow: sizzleActive
              ? "0 0 45px rgba(239, 126, 42, 0.4)"
              : isHovered
              ? "0 0 30px rgba(253, 186, 116, 0.15)"
              : "0 10px 30px rgba(0,0,0,0.5)",
          }}
        >
          {/* Glowing embers background */}
          <div className="absolute inset-x-0 bottom-0 top-1/2 bg-gradient-to-t from-orange-900/40 to-transparent pointer-events-none" />
          
          {/* Main steak photo floating */}
          <img
            src={steakTexturePath}
            alt="Australian Prime Steak on Grill"
            className={`w-4/5 aspect-square rounded-full object-cover transition-transform duration-500 shadow-2xl border-2 border-stone-800 ${
              sizzleActive ? "animate-[spin_1.2s_ease-out_infinite]" : "animate-[spin_20s_linear_infinite]"
            }`}
            referrerPolicy="no-referrer"
          />

          {/* Glowing Spark effects overlay */}
          {sizzleActive && (
            <div className="absolute inset-0 bg-transparent flex flex-wrap gap-2 justify-center items-center pointer-events-none">
              <div className="w-1.5 h-1.5 bg-orange-500 rounded-full animate-ping absolute top-12 left-12" />
              <div className="w-1 h-1 bg-amber-400 rounded-full animate-ping absolute bottom-24 right-16" />
              <div className="w-2 h-2 bg-yellow-400 rounded-full animate-ping absolute top-20 right-28" />
              <div className="w-1.5 h-1.5 bg-red-500 rounded-full animate-ping absolute bottom-12 left-24" />
            </div>
          )}

          <div className="absolute bottom-4 left-0 right-0 text-center flex items-center justify-center gap-1.5 pointer-events-none bg-stone-900/80 mx-auto w-fit py-1 px-3 rounded-full border border-stone-800">
            <Rotate3d className="w-4.5 h-4.5 text-orange-500" />
            <span className="text-xs font-mono text-orange-200 uppercase tracking-widest font-semibold">Ketuk untuk Memutar</span>
          </div>
        </div>
      ) : (
        /* The gorgeous Three.js 3D WebGL Canvas Container */
        <div
          id="3d-steak-three-mesh"
          ref={mountRef}
          onClick={handleInteractionClick}
          onMouseMove={handleMouseMove}
          onMouseEnter={handleMouseEnter}
          onMouseLeave={handleMouseLeave}
          onTouchStart={handleTouchStart}
          onTouchMove={handleTouchMove}
          className="w-full h-full cursor-pointer relative"
          style={{ touchAction: "none" }}
        >
          {/* Micro interaction guidance overlays */}
          <div className="absolute bottom-1/8 left-1/2 -translate-x-1/2 flex items-center gap-1.5 pointer-events-none px-3.5 py-1.5 bg-zinc-950/70 backdrop-blur-md rounded-full border border-amber-500/20 shadow-lg select-none">
            <Flame className={`w-4 h-4 text-orange-500 ${sizzleActive ? "animate-pulse" : ""}`} />
            <span className="text-[10px] sm:text-xs font-mono text-orange-200 uppercase tracking-widest font-semibold">
              {sizzleActive ? "Memanggang Membara!" : "Ketuk untuk Membakar"}
            </span>
          </div>

          {/* Sparks count indicator for gamified touch */}
          {clickCount > 0 && (
            <div className="absolute top-8 right-8 bg-orange-600/10 border border-orange-500/30 text-orange-400 font-mono text-xs px-2.5 py-1 rounded-md animate-bounce">
              🔥 Sizzle {clickCount}x
            </div>
          )}
        </div>
      )}

      {/* Floating Sparkles absolute graphic design borders around the 3D target */}
      <div className="absolute top-4 left-6 pointer-events-none flex items-center gap-1 font-mono text-[9px] text-zinc-500 uppercase tracking-widest">
        <span>GRILL ENGINE v3.0</span>
      </div>
      <div className="absolute bottom-6 right-6 pointer-events-none flex items-center gap-1 font-mono text-[9px] text-amber-500/80">
        <Sparkles className="w-3 h-3 text-orange-500 animate-spin" />
        <span>THREE.JS IMMERSIVE 3D</span>
      </div>
    </div>
  );
}
